###################################
#       MultiLogin    --config
#                   By Caa Moe.
###################################

# 存放所有的Yggdrasil验证服务器，
# 正版Yggdrasil在officialServices节点中单独设置。
services:

  # 插件标记名称，一旦设置请谨慎修改。
  # 该标记作为识别用户的验证服务器，为系统标记.胡乱更改很有可能会导致safetyML无法验证身份。
  # 您可以仿写此节点用来添加新的Yggdrasil验证服务器。
  littleSkin:

    # 验证服务器的别称，可以随意修改。
    name: "LS皮肤站"

    # 验证服务器地址。
    url: "https://mcskin.littleservice.cn/api/yggdrasil"

    # 转换UUID
    # 当某名玩家第一次在此节点所设置的验证服务器中验证通过后，游戏内的UUID会按照此节点所填写的规则来生成
    # 目前只支持以下值:
    #   default   -使用Yggdrasil验证服务器提供的UUID
    #   offline   -自动生成离线UUID（盗版UUID）
    # 所有生成的结果均会缓存至swap_uuid.json中。
    # 该值的优先级低于swap_uuid.json文件内的值。
    # 请谨慎设置该节点，很有可能会致使玩家数据错乱！
    convUuid: default

# 正版验证服务器的别称，可以随意修改。
officialName: "正版"


# 使用正版Yggdrasil验证服务器
# 关闭ta将拒绝所有使用正版登入的玩家登入游戏
officialServices: true

# 正版转换UUID
# 当某名玩家第一次在正版验证服务器中验证通过后，游戏内的UUID会按照此节点所填写的规则来生成
# 目前只支持以下值:
#   default   -使用Yggdrasil验证服务器提供的UUID
#   offline   -自动生成离线UUID（盗版UUID）
# 所有生成的结果均会缓存至swap_uuid.json中。
# 该值的优先级低于swap_uuid.json文件内的值。
# 请谨慎设置该节点，很有可能会致使玩家数据错乱！
officialConvUuid: default

# 全局转换UUID
# 当某名玩家第一次在正版验证服务器中验证通过后，游戏内的UUID会按照此节点所填写的规则来生成
# 目前只支持以下值:
#   default   -使用Yggdrasil验证服务器提供的UUID
#   offline   -自动生成离线UUID（盗版UUID）
# 所有生成的结果均会缓存至swap_uuid.json中。
# 该值的优先级低于convUuid、officialConvUuid节点中的值。
# 请谨慎设置该节点，很有可能会致使玩家数据错乱！
overAllConvUuid: default

# 服务器内是否允许重名
# 判定规则：服务器将会记录并且缓存玩家的登入数据，并更新账户的name，当有新老玩家登入到游戏中，系统会判断玩家的name是否被其他缓存用户占用。
#    如若被占用，系统将会拒绝他的登入请求，直到name可用为止。
noRepeatedName: true