###################################
#       MultiLogin
#              --config
###################################

# 存放所有的Yggdrasil验证服务器，
# 正版Yggdrasil在officialServices节点中单独设置。
services:

  # 插件标记名称，一旦设置请谨慎修改。
  # official值为保留关键词，请勿应用于此标记名称上！
  # 该标记作为识别用户的验证服务器，为系统标记.胡乱更改很有可能会导致safetyML无法验证身份。
  # 您可以仿写此节点用来添加新的Yggdrasil验证服务器。
  littleSkin:

    # 验证服务器的别称，可以随意修改。
    name: "LS皮肤站"

    # 验证服务器地址。
    url: "https://mcskin.littleservice.cn/api/yggdrasil"

    # 转换UUID
    # 当某名玩家第一次在此节点所设置的验证服务器中验证通过后，游戏内的UUID会按照此节点所填写的规则来生成
    # 目前只支持以下值:
    #   DEFAULT   -使用Yggdrasil验证服务器提供的UUID
    #   OFFLINE   -自动生成离线UUID（盗版UUID）
    # 所有生成的结果均会缓存至swap_uuid.json中。
    # 该值的优先级低于swap_uuid.json文件内的值。
    # 请谨慎设置该节点，很有可能会致使玩家数据错乱！
    convUuid: DEFAULT

# 正版验证服务器的别称，可以随意修改。
officialName: "正版"


# 使用正版Yggdrasil验证服务器
# 关闭ta将拒绝所有使用正版登入的玩家登入游戏
officialServices: true

# 正版转换UUID
# 当某名玩家第一次在正版验证服务器中验证通过后，游戏内的UUID会按照此节点所填写的规则来生成
# 目前只支持以下值:
#   DEFAULT   -使用Yggdrasil验证服务器提供的UUID
#   OFFLINE   -自动生成离线UUID（盗版UUID）
# 所有生成的结果均会缓存至swap_uuid.json中。
# 该值的优先级低于swap_uuid.json文件内的值。
# 请谨慎设置该节点，很有可能会致使玩家数据错乱！
officialConvUuid: DEFAULT

# 服务器内是否允许重名
# 判定规则：服务器将会记录并且缓存玩家的登入数据，并更新账户的name，当有新老玩家登入到游戏中，系统会判断玩家的name是否被其他缓存用户占用。
#    如若被占用，系统将会拒绝他的登入请求，直到name可用为止。
noRepeatedName: true

##############
#   Message
##############

msgNoAdopt: "§c验证未能通过，请重新尝试"
msgNoChae: "§c您只能通过指定的验证方式登入游戏"
msgRushName: "§c您的ID已被抢注，请重新设置您的ID"
msgNoWhitelist: "§c您没有白名单"

msgInvCmd: "§c无效的命令"
msgAddWhitelist: "§a已将%s添加至白名单"
msgAddWhitelistAlready: "§c请勿重复将%s添加至白名单"
msgDelWhitelistInGame: "§c管理员已移除您的白名单权限"
msgDelWhitelist: "§a已移除%s的白名单"
msgDelWhitelistAlready: "§c%s并不在白名单中"
msgOpenWhitelist: "§a已开启白名单"
msgOpenWhitelistAlready: "§c请勿重复开启白名单"
msgCloseWhitelist: "§a已关闭白名单"
msgCloseWhitelistAlready: "§c请勿重复关闭白名单"
msgWhitelistListNoth: "§c白名单内没有玩家"
msgWhitelistListN: "§白名单内一共有%d名玩家：%s"