name: MultiLogin
main: moe.caa.multilogin.bukkit.MultiLoginBukkit
version: @version@
author: CaaMoe,ksqeib
softdepend: [ PlaceholderAPI ]
libraries:
  - 'mysql:mysql-connector-java:8.0.11'
  - 'com.zaxxer:HikariCP:4.0.3'
  - 'com.h2database:h2:1.4.200'
commands:
  whitelist:
  multilogin: