#####################################################################
#
#     配置文件格式为 ‘YAML’，推荐使用 Visual Studio Code 浏览和编辑。
#          前往 ‘https://yaml.org/’ 查阅 YAML 配置语法
#
#           除了布尔值和整数、浮点数之外的配置，请使用引号包裹起来。
#
#    BUG REPORTS:   https://github.com/CaaMoe/MultiLogin/issues
#####################################################################

# 插件数据设置
sql:

  # 数据库类型设置
  #
  # 请使用以下值:
  #   H2
  #   MYSQL
  # 默认值 ‘H2’
  backend: 'H2'

  # 数据库访问地址
  #
  # 默认值 ‘127.0.0.1’
  ip: 127.0.0.1

  # 端口
  #
  # 默认值 ‘3306’
  port: 3306

  # 用户名
  #
  # 默认值 ‘root’
  username: root

  # 访问密码
  #
  # 默认值 ‘root’
  password: root

  # 数据库名称
  #
  # 默认值 ‘multilogin’
  database: multilogin

  # 使用的数据表前缀。
  #
  # 使用时将会补充后缀符号 ‘_’
  # 请不要随意更改它，否则数据将消失
  # 默认值 ‘multilogin’
  tablePrefix: multilogin

  # 高级设定，指定连接 URL
  #
  # 默认值 ’‘
  connectUrl: ''