###################################
#       MultiLogin -
#              --config
###################################

# 是否向终端输出更多调试信息。
# 若为 true, 终端也许会很吵闹。
# 默认值 'false'
debug: false

# 在这里，设置所有的 Yggdrasil 账户验证服务器。
services:

  # 这是一个示例配置：
  # 节点名称 'demo' 作为混合验证系统识别 Yggdrasil 验证服务器唯一性的依据，一旦设置请不要随意的去改动它，
  # 胡乱更改节点名称将会导致系统无法验证用户身份而被拒绝用户登入请求。
  # 您可以仿写此节点用来添加新的 Yggdrasil 账户验证服务器。
  demo:

    # 启用该验证服务器。
    # 值为 'false' 时将不添加该 Yggdrasil 账户验证服务器到混合登入系统中去，将拒绝一切使用该 Yggdrasil 账户验证服务器的球员登入游戏。
    # 默认值 'true'
    enable: false

    # 该账户验证服务器中的别称。
    # 不用于父节点名称，此节点的值可以随意修改。
    # 必填值，在 Bukkit 服务端中作为变量传递。
    name: "Demo Yggdrasil"

    # Yggdrasil 账户验证服务器的基本属性和信息设置。
    body:

      # Yggdrasil 账户验证服务器服务端 hasJoined 阶段部分验证请求链接设置。
      # 此节点必须指定完整的请求链接。
      # 其中 GET 请求中的占位变量 {0} 或 {username} 表示 username，占位变量 {1} 或 {serverId} 表示 serverId，
      #        占位变量 {2} 或 {passIpContent} 表示 passIpContent 节点所设置的内容。
      # 请求的 URL 对大小写非常敏感，设置需谨慎！
      # 一些例子 "https://example.com/session/minecraft/hasJoined?username={username}&serverId={serverId}"
      # 必填值！
      url: "https://example.com/session/minecraft/hasJoined?username={username}&serverId={serverId}{passIpContent}"

      # hasJoined 阶段使用 POST（报文） 请求的方式验证账户身份。
      # 绝大多数下， Yggdrasil 账户验证服务器 hasJoined 阶段都采用 GET 请求方式验证用户数据的，
      # 如果你不了解当前 Yggdrasil 验证流程的话，请勿擅自改动它。
      # 默认值 'false'
      postMode: false

      # hasJoined 阶段是否向 Yggdrasil 账户验证服务器传递用户 IP 信息，如果存在。
      # 默认值 'false'
      passIp: false

      # 设置 url 节点 {2} 或 {passIpContent} 变量内容，
      # 其中，变量 {0} 或 {ip} 为所获取到的 IP 信息。
      # 仅当 passIp 节点为 true 时此节点有效。
      # 请求的 URL 对大小写非常敏感，设置需谨慎！
      # 一些例子 ', "ip": "{ip}"'、 '&ip={ip}'
      # 默认值 '&ip={ip}'
      passIpContent: "&ip={ip}"

      # 设置 post 的请求内容。
      # 其中 POST 请求中的占位变量 {0} 或 {username} 表示 username，占位变量 {1} 或 {serverId} 表示 serverId，
      #        占位变量 {2} 或 {passIpContent} 表示 passIpContent 节点所设置的内容。
      # 请求的 URL 对大小写非常敏感，设置需谨慎！
      # 一些例子 '{"username":"{username}", "serverId":"{serverId}"{passIpContent}}'、 '{"username":"{username}", "serverId":"{serverId}"}'
      # 默认值 '{"username":"{username}", "serverId":"{serverId}"}'
      postContent: '{"username":"{username}", "serverId":"{serverId}"}'

    # 当玩家首次登入且使用当前 Yggdrasil 账户验证服务器验明身份后，它的游戏内 UUID 生成规则设置：
    # 目前只支持以下值:
    #   DEFAULT   - 使用 Yggdrasil 账户证服务器提供的在线 UUID
    #   OFFLINE   - 自动生成离线 UUID（盗版UUID）
    #   RANDOM    - 随机 UUID
    # 请谨慎设置和修改此节点，避免增加日后维护的心智负担。
    # 为避免触发 Paper 端的某些机制，强烈建议此值为 DEFAULT
    # 默认值 'DEFAULT'
    convUuid: DEFAULT

    # 是否当首次登入的玩家生成的游戏内 UUID 已存在，自动更正到随机的 UUID。
    # 请尽量保持此值为 true ，除非您了解后果是什么（虽然几率很小）。
    # 默认值 'true'
    convRepeat: true

    # 当前 Yggdrasil 账户验证服务器下的玩家允许设置的用户名正则设置。
    # 若不匹配将会拒绝当前玩家的登入请求
    # 如果此值留空或未设置，则应用根节点下 'nameAllowedRegular' 节点值。
    # 默认值 ''
    nameAllowedRegular: ''

    # 是否为当前验证服务器单独开启白名单。
    # 当全局白名单为 true 时，此节点无效。
    # 默认值: false
    whitelist: false

    # 当玩家登入时，服务器中已有 相同游戏内 UUID 的情况是否拒绝玩家登入。
    # 若为 false 将把游戏内相同 UUID 的玩家踢出，允许验证中的玩家登入（原版默认）
    # 若为 true 则拒绝当前的登入请求
    # 默认值: false
    refuseRepeatedLogin: false

    # 验证错误重试次数
    # 默认值: 1
    authRetry: 1

    # 当前 Yggdrasil 账户验证服务器是否具有绝对的 ID 使用、更换权限。
    # 若为 'true', 其他 Yggdrasil 账户验证服务器下的玩家都不能在服务器内抢夺和使用此验证服务器下玩家的 ID 使用权限。
    # 默认值 'false'
    safeId: false

# 设置所有网络请求的超时时间
# 默认值 '10000'
servicesTimeOut: 10000

# 全局白名单开关
# 默认值 'true'
whitelist: true

# 玩家允许设置的用户名正则，不匹配将会拒绝登入请求。
# 当当前 Yggdrasil 账户验证服务器设置中对应设置节点存在值时，此节点对于该验证服务器无效。
# 默认值 ''
nameAllowedRegular: '^[0-9a-zA-Z_]{1,16}$'

# 插件数据的存放方式
sql:

  # 数据库类型设置
  # 目前至支持以下值：
  # H2
  # MYSQL
  # 默认值 'H2'
  backend: H2

  # 数据库地址
  # 默认值 '127.0.0.1'
  ip: '127.0.0.1'

  # 数据库端口
  # 默认值 '3306'
  port: 3306

  # 数据库用户名
  # 默认值 'root'
  username: 'root'

  # 数据库密码
  # 默认值 '12345'
  password: '12345'

  # 数据库名称
  # 默认值 'multilogin'
  database: 'multilogin'

  # 前缀
  # 默认值 'multilogin'
  prefix: 'multilogin'

  # 指定 MySQL 链接 URL
  # 其中占位变量 {0} 或 {ip} 表示 ip，占位变量 {1} 或 {port} 表示 port，
  #        占位变量 {2} 或 {database} 表示 database 。
  # URL 对大小写非常敏感，设置需谨慎！
  # 值留空默认，建议不对其进行设置。
  # 默认值 'jdbc:mysql://{ip}:{port}/{database}?autoReconnect=true&useUnicode=true&amp&characterEncoding=UTF-8&useSSL=false'
  mysqlUrl: ''

  # 指定 H2 链接 URL
  # 其中占位变量 {0} 或 {file_path} 表示默认的数据库文件绝对路径（不包含数据库文件扩展名 '.mv.db'）。
  # 一般的，{file_path} 变量为 '$server$/plugins/MultiLogin/multilogin' ($server$ 仅在此表示服务端文件路径)
  # URL 对大小写非常敏感，设置需谨慎！
  # 值留空默认，建议不对其进行设置。
  # 默认值 'jdbc:h2:{file_path};TRACE_LEVEL_FILE=0;TRACE_LEVEL_SYSTEM_OUT=0'
  h2Url: ''